### ISSUE TITLE
Xen implementation of `libkvmchan_client_init` blocks

### ISSUE THREAD

**Issue by nrgaway** [shawnanastasio/libkvmchan#20]
### libvchan_client_init
I have had some strange issues where _libvchand_ would fail to connect some _qrexec_ client connections initiated from the host when the VM server connection had not been started.  As I mentioned previously I had added code to `qrexec-daemon.c` to keep retrying the connection every second with a timeout period.  After implementing `qubes-gui-agent`, I was getting other similar failures.  I discovered that the the _Xen_ implementation of `libvchan_client_init` blocks and does not support connection timeout. This is described within the main function of 'core-qrexec/daemon/qrexec.client.c'. The code uses alarm(2) as a timeout.  Therefore I updated the `libvchan_client_init` within `core-vchan-kvm` to be blocking so it would behave in the expected manner.  Once I implemented this change things started working and communicating.

```
libvchan_t *libvchan_client_init(int domain, int port) {
    /**
     * It appears the Xen implementation of `libvchan_client_init` is blocking
     * and does not support connection timeout as described within the main
     * function of 'core-qrexec/daemon/qrexec.client.c'. The code uses alarm(2)
     * as a timeout.
     */
    libvchan_t *vchan;

    vchan = libkvmchan_client_init(domain, port);
    while (!vchan) {
        usleep(1 * 1000 * 1000);
        vchan = libkvmchan_client_init(domain, port);
    }
    return vchan;
}
```

However I have not submitted a pull-request for this change as it does create an additional issue and was not sure if you would prefer to handle blocking within the _libkvmchan_ code.  The issue that this code creates is that it keeps trying to reconnect even if the VM is no longer running :)  So it may be better to handle it within _libkvmchan_, or need to add code on each iteration to return if VM is not running either by communicating with _Virsh_ or _Qubes_ for VM status, or just confirm process id still exists for VM.

**Comment by shawnanastasio** [comment]
Oh, when I implemented client_init I didn't realize the Xen behavior was to block. Is the timeout user-controllable or is it just hardcoded in Xen's vchan? In any case, this probably belongs in libkvmchan's library.c implementation with select(2) or something used to implement the timeout. I can implement it or you can submit a PR, just let me know.

**Comment by nrgaway** [comment]
I agree it belongs in libkvmchan's library.  The _Xen_ client_init has has no timeout option as far as I know (just looked at the [_Xen_ code](https://xenbits.xen.org/gitweb/?p=xen.git;a=blob;f=tools/libvchan/init.c;h=ad4b64fbe3d372025ba7fa1355bd1a23d7773b86;hb=refs/heads/master#l393)). The alarm I was referring to was a comment made in the _Qubes_ [core-qrexec/daemon/qrexec-client.c](https://github.com/QubesOS/qubes-core-qrexec/blob/a751d4378ba56318c3a0a63d862b4b21ff9136db/daemon/qrexec-client.c#L609) code which sets an alarm due to the _Xen_ client_init function having no timeout.

Go ahead and implement it since I am still not familiar enough with the internals.  Be aware that even though it is blocking it should return (false?) if the domain is no longer running.  I came across that issue when implementing the above where it still attempted to connect to a domain that was no longer running.
